title: Greg Pfadenhauer
email: greg.pfadenhauer@gmail.com

url: "http://gregpf.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  greg-pf

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-feed
